from .base import Base
from .pais import Pais
from .localidad import Localidad
from .grado import Grado
from .facultad import Facultad
from .universidad import Universidad
from .materia import Materia
from .especialidad import Especialidad
from .orientacion import Orientacion
from .plan import Plan
