from .pais_service import *
from .localidad_service import *
from .grado_service import *
from .facultad_service import *
from .universidad_service import *
from .materia_service import *
from .especialidad_service import *
from .orientacion_service import *
from .plan_service import *
